[project]
name = "kkgepo"
version = "0.1.0"
requires-python = ">=3.8"
# No external runtime dependencies
dependencies = [
    "pyyaml>=6.0.2",
]

[project.optional-dependencies]
develop = [
    "pytest>=7.0",
]

[dependency-groups]
dev = [
    "pex>=2.40.2",
    "pytest>=8.3.5",
]
